# Netlify configuration file

[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "next dev"

# Plugin required for Next.js SSR and API routes
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Set these securely in Netlify UI (Site Settings → Environment Variables)
  MONGODB_URI = "your_mongodb_connection_string"
  JWT_SECRET = "your-super-secret-key-that-is-long-and-secure"
  TELEGRAM_BOT_TOKEN = "your_telegram_bot_token"
